services:
  dataomni_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      # ADD YOUR OPENAI API KEY HERE
      - OPENAI_API_KEY=
